import type {
  Challenge,
  Startup,
  Proposal,
  Evaluation,
  Pilot,
  ProcurementItem,
  ChangelogEntry,
} from "@/types";

// â”€â”€ Seed Challenges â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedChallenges: Challenge[] = [
  {
    id: "ch_001",
    title: "AI-Powered Pothole Detection & Road Quality Monitoring",
    department: "Ministry of Road Transport & Highways",
    description:
      "Develop an AI-based system using computer vision and IoT sensors to automatically detect, classify, and geolocate potholes and road surface defects in real-time.",
    problemStatement:
      "India loses â‚¹10,000 Cr annually due to poor road maintenance. Current manual inspection is slow, inconsistent, and covers less than 30% of national highways annually. We need an automated, scalable solution that can process data from existing CCTV infrastructure.",
    budget: 5_00_00_000,
    timeline: "12 months",
    targetKPIs: [
      "Detection accuracy â‰¥ 92%",
      "Coverage of 50,000 km of highways in Phase 1",
      "Response time from detection to maintenance ticket: < 24 hrs",
      "Cost reduction in road maintenance: 30%",
    ],
    domains: ["AI/ML", "Computer Vision", "IoT", "GIS"],
    status: "applications_open",
    publishedAt: "2024-06-15T09:00:00Z",
    deadline: "2024-08-30T23:59:59Z",
    applicationsCount: 23,
    createdBy: "gov_user_001",
    createdAt: "2024-06-10T14:22:00Z",
    updatedAt: "2024-06-15T09:00:00Z",
    aiSuggestions: [
      "Consider adding data privacy KPIs for CCTV footage processing",
      "Specify minimum IoT sensor specifications for interoperability",
      "Add edge computing requirements for real-time processing",
    ],
  },
  {
    id: "ch_002",
    title: "Multilingual AI Grievance Redressal Chatbot for Citizen Services",
    department: "Department of Administrative Reforms & Public Grievances",
    description:
      "Build a multilingual conversational AI platform capable of handling citizen grievances in 22 scheduled languages with 99% uptime SLA and DISHA-compliant data isolation.",
    problemStatement:
      "Over 4 crore grievances are filed annually on CPGRAMS. Resolution rates are at 67% due to language barriers, routing inefficiencies, and manual triage. A smart AI layer is needed to automate triage, translate grievances, and route them to the correct department within 2 hours.",
    budget: 3_50_00_000,
    timeline: "9 months",
    targetKPIs: [
      "Support 22 scheduled Indian languages",
      "Grievance triage accuracy â‰¥ 95%",
      "Auto-resolution rate for Tier-1 queries â‰¥ 40%",
      "Average resolution time reduction: 60%",
    ],
    domains: ["NLP", "Conversational AI", "Multilingual AI", "Government Tech"],
    status: "evaluation",
    publishedAt: "2024-05-01T09:00:00Z",
    deadline: "2024-07-15T23:59:59Z",
    applicationsCount: 31,
    createdBy: "gov_user_002",
    createdAt: "2024-04-25T10:00:00Z",
    updatedAt: "2024-06-20T11:00:00Z",
    aiSuggestions: [
      "Include Braille/screen-reader accessibility requirements",
      "Specify CERT-In compliance for data handling",
    ],
  },
  {
    id: "ch_003",
    title: "Blockchain-Based Land Records Digitization & Mutation Tracking",
    department: "Ministry of Rural Development",
    description:
      "Create a tamper-proof, blockchain-anchored land records system that integrates with existing state Bhu-Naksha and Dharani portals to prevent fraudulent mutations.",
    problemStatement:
      "Land disputes account for 66% of all pending court cases in India. Fraudulent land mutations cost farmers â‚¹40,000 Cr annually. A blockchain-based immutable record system will prevent unauthorized changes and provide a transparent audit trail for all mutations.",
    budget: 8_00_00_000,
    timeline: "18 months",
    targetKPIs: [
      "Zero fraudulent mutations in blockchain-enrolled records",
      "Mutation processing time: < 7 days (from 90+ days)",
      "Integration with 10 state portals in Phase 1",
      "99.9% system uptime",
    ],
    domains: ["Blockchain", "GovTech", "Legal Tech", "Rural Development"],
    status: "sandbox",
    publishedAt: "2024-03-01T09:00:00Z",
    deadline: "2024-05-15T23:59:59Z",
    applicationsCount: 15,
    createdBy: "gov_user_001",
    createdAt: "2024-02-20T09:00:00Z",
    updatedAt: "2024-07-01T14:00:00Z",
    aiSuggestions: [],
  },
  {
    id: "ch_004",
    title: "Smart Energy Metering & Theft Detection for Rural Electrification",
    department: "Ministry of Power",
    description:
      "Deploy smart prepaid meters with AI-powered energy theft detection across rural feeders under the PM-KUSUM scheme, reducing AT&C losses below 12%.",
    problemStatement:
      "AT&C losses in rural distribution stand at 32%, costing DISCOMs â‚¹1.2 lakh Cr annually. Manual meter reading is error-prone and expensive. Smart metering with AI anomaly detection will enable real-time loss identification and remote disconnection.",
    budget: 12_00_00_000,
    timeline: "24 months",
    targetKPIs: [
      "AT&C loss reduction: from 32% to < 12%",
      "Theft detection accuracy: â‰¥ 90%",
      "Remote meter reading coverage: 100%",
      "Billing accuracy improvement: â‰¥ 98%",
    ],
    domains: ["IoT", "AI/ML", "Energy Tech", "Rural Development"],
    status: "draft",
    publishedAt: null,
    deadline: "2024-10-31T23:59:59Z",
    applicationsCount: 0,
    createdBy: "gov_user_003",
    createdAt: "2024-07-20T10:00:00Z",
    updatedAt: "2024-07-20T10:00:00Z",
    aiSuggestions: [
      "Add cybersecurity specifications for meter firmware",
      "Include interoperability with existing SCADA systems",
      "Define data retention and privacy policy for energy consumption data",
    ],
  },
  {
    id: "ch_005",
    title: "Predictive Health Analytics for District Hospital Resource Planning",
    department: "Ministry of Health & Family Welfare",
    description:
      "Develop a predictive analytics platform for district hospitals to forecast patient loads, optimize bed occupancy, and pre-position essential medicines using historical data.",
    problemStatement:
      "District hospitals face 40% bed occupancy crises during seasonal disease outbreaks. Medicine stockouts affect 30% of PHCs monthly. Predictive AI can reduce these gaps by analyzing patient inflow patterns, seasonal trends, and demographic data.",
    budget: 4_00_00_000,
    timeline: "10 months",
    targetKPIs: [
      "Prediction accuracy for weekly patient load: â‰¥ 85%",
      "Medicine stockout reduction: 70%",
      "Bed occupancy optimization: â‰¥ 20% improvement",
      "Coverage: 200 district hospitals in Phase 1",
    ],
    domains: ["Health Tech", "AI/ML", "Data Analytics", "Government Tech"],
    status: "procurement",
    publishedAt: "2024-01-10T09:00:00Z",
    deadline: "2024-03-31T23:59:59Z",
    applicationsCount: 19,
    createdBy: "gov_user_002",
    createdAt: "2024-01-05T09:00:00Z",
    updatedAt: "2024-07-15T09:00:00Z",
    aiSuggestions: [],
  },
];

// â”€â”€ Seed Startups â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedStartups: Startup[] = [
  {
    id: "st_001",
    name: "VisionAI Labs Pvt. Ltd.",
    dpiitNumber: "DPIIT132847",
    foundedYear: 2020,
    domains: ["AI/ML", "Computer Vision", "IoT"],
    trlLevel: 7,
    teamSize: 45,
    annualTurnover: 280,
    hasGovernmentExperience: false,
    description:
      "Deep-tech startup specializing in real-time computer vision solutions for infrastructure monitoring, traffic management, and public safety.",
    contactEmail: "partnerships@visionailabs.in",
    website: "https://visionailabs.in",
    eligibilityStatus: "verified",
    waivers: ["prior_experience", "turnover"],
    createdAt: "2024-03-15T09:00:00Z",
  },
  {
    id: "st_002",
    name: "BharatNLP Technologies",
    dpiitNumber: "DPIIT198562",
    foundedYear: 2019,
    domains: ["NLP", "Conversational AI", "Multilingual AI"],
    trlLevel: 8,
    teamSize: 62,
    annualTurnover: 520,
    hasGovernmentExperience: true,
    description:
      "India's leading multilingual NLP startup with production-grade models for 18 Indian languages, serving 3 state governments.",
    contactEmail: "bd@bharatnlp.ai",
    website: "https://bharatnlp.ai",
    eligibilityStatus: "verified",
    waivers: [],
    createdAt: "2024-01-20T09:00:00Z",
  },
  {
    id: "st_003",
    name: "ChainGuard Systems",
    dpiitNumber: "DPIIT201934",
    foundedYear: 2021,
    domains: ["Blockchain", "GovTech", "Legal Tech"],
    trlLevel: 6,
    teamSize: 28,
    annualTurnover: 95,
    hasGovernmentExperience: false,
    description:
      "Enterprise blockchain solutions for government record-keeping, supply chain traceability, and document verification.",
    contactEmail: "hello@chainguard.tech",
    website: "https://chainguard.tech",
    eligibilityStatus: "verified",
    waivers: ["prior_experience", "turnover"],
    createdAt: "2024-04-01T09:00:00Z",
  },
  {
    id: "st_004",
    name: "SmartGrid Innovations",
    dpiitNumber: "DPIIT178290",
    foundedYear: 2018,
    domains: ["IoT", "Energy Tech", "AI/ML"],
    trlLevel: 8,
    teamSize: 87,
    annualTurnover: 1200,
    hasGovernmentExperience: true,
    description:
      "Pioneer in smart metering and grid optimization with deployments across 3 DISCOMs and 500,000+ smart meters installed.",
    contactEmail: "contracts@smartgridinnovations.in",
    eligibilityStatus: "verified",
    waivers: [],
    createdAt: "2024-02-10T09:00:00Z",
  },
  {
    id: "st_005",
    name: "HealthPredict Analytics",
    dpiitNumber: "DPIIT245678",
    foundedYear: 2022,
    domains: ["Health Tech", "AI/ML", "Data Analytics"],
    trlLevel: 5,
    teamSize: 18,
    annualTurnover: 45,
    hasGovernmentExperience: false,
    description:
      "AI-driven predictive analytics for healthcare resource optimization, focusing on rural and semi-urban health infrastructure.",
    contactEmail: "team@healthpredict.ai",
    eligibilityStatus: "verified",
    waivers: ["prior_experience", "turnover"],
    createdAt: "2024-05-05T09:00:00Z",
  },
];

// â”€â”€ Seed Proposals â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedProposals: Proposal[] = [
  {
    id: "pr_001",
    challengeId: "ch_001",
    startupId: "st_001",
    startupName: "VisionAI Labs Pvt. Ltd.",
    trlLevel: 7,
    methodology:
      "Deploy YOLO-v8 based real-time pothole detection models on edge computing nodes connected to existing NHAI CCTV cameras. Use federated learning to improve model accuracy across diverse road conditions. GIS integration for automated work-order generation.",
    sandboxTimeline: "3 months pilot on NH-48 corridor (Delhi-Mumbai Expressway segment)",
    technicalApproach:
      "Edge AI inference pipeline with < 200ms latency. Custom dataset of 2M annotated Indian road defect images. Integration with NHAI's RAMS (Road Asset Management System) via REST APIs.",
    estimatedCost: 1_80_00_000,
    status: "under_review",
    matchScore: 91,
    matchFactors: [
      { factor: "Semantic Similarity", score: 36, maxScore: 40, explanation: "Problem domain and technical keywords align strongly" },
      { factor: "Domain Compatibility", score: 28, maxScore: 30, explanation: "Computer Vision and IoT are core competencies" },
      { factor: "Readiness Level", score: 27, maxScore: 30, explanation: "TRL 7 with existing CCTV deployment experience" },
    ],
    submittedAt: "2024-07-15T11:30:00Z",
    updatedAt: "2024-07-15T11:30:00Z",
  },
  {
    id: "pr_002",
    challengeId: "ch_002",
    startupId: "st_002",
    startupName: "BharatNLP Technologies",
    trlLevel: 8,
    methodology:
      "Fine-tuned mBERT + IndicBERT ensemble for grievance classification and routing. Custom ASR pipeline for voice grievances in regional languages. Rule-based + ML hybrid for auto-resolution of Tier-1 queries.",
    sandboxTimeline: "2 months pilot on CPGRAMS with 5 departments (Railways, Post, Income Tax, EPF, Customs)",
    technicalApproach:
      "Microservices architecture on NIC cloud. DISHA-compliant data residency. 22-language support with 94.2% NER accuracy on IndoNLP benchmark. Integration with existing CPGRAMS via SOAP/REST gateway.",
    estimatedCost: 1_20_00_000,
    status: "evaluated",
    matchScore: 88,
    matchFactors: [
      { factor: "Semantic Similarity", score: 34, maxScore: 40, explanation: "NLP and multilingual AI are exact domain matches" },
      { factor: "Domain Compatibility", score: 27, maxScore: 30, explanation: "Strong language portfolio for all 22 scheduled languages" },
      { factor: "Readiness Level", score: 27, maxScore: 30, explanation: "TRL 8 with 3 state government deployments" },
    ],
    submittedAt: "2024-06-20T14:00:00Z",
    updatedAt: "2024-07-10T09:00:00Z",
  },
  {
    id: "pr_003",
    challengeId: "ch_003",
    startupId: "st_003",
    startupName: "ChainGuard Systems",
    trlLevel: 6,
    methodology:
      "Hyperledger Fabric-based permissioned blockchain with NIC-hosted validator nodes. Smart contracts for mutation workflows with mandatory multi-party sign-off (Tehsildar + Collector + Citizen). QR-code based certificate verification for citizens.",
    sandboxTimeline: "4 months pilot in 2 districts of Telangana (Dharani integration) and 2 districts of Rajasthan",
    technicalApproach:
      "Fabric 2.4 with Byzantine fault-tolerant PBFT consensus. Integration adapters for Bhu-Naksha, Dharani, and DILRMP. Mobile app for farmer self-verification. Aadhaar eKYC integration via UIDAI APIs.",
    estimatedCost: 2_80_00_000,
    status: "approved",
    matchScore: 84,
    matchFactors: [
      { factor: "Semantic Similarity", score: 33, maxScore: 40, explanation: "Blockchain for land records is core solution area" },
      { factor: "Domain Compatibility", score: 27, maxScore: 30, explanation: "Strong GovTech and Legal Tech background" },
      { factor: "Readiness Level", score: 24, maxScore: 30, explanation: "TRL 6, needs additional sandbox validation" },
    ],
    submittedAt: "2024-04-25T10:00:00Z",
    updatedAt: "2024-05-20T15:00:00Z",
  },
  {
    id: "pr_004",
    challengeId: "ch_005",
    startupId: "st_005",
    startupName: "HealthPredict Analytics",
    trlLevel: 5,
    methodology:
      "Ensemble of LSTM time-series models + XGBoost for patient load prediction. Automated procurement recommendation engine for medicine stock. Integration with HMIS (Health Management Information System) for data ingestion.",
    sandboxTimeline: "3 months pilot in 10 district hospitals across Madhya Pradesh",
    technicalApproach:
      "Cloud-agnostic deployment (AWS/Azure/NIC). ABDM-compliant data standards. Real-time dashboard for CMO and district health officers. Automated reorder triggers via NHM procurement portal APIs.",
    estimatedCost: 95_00_000,
    status: "approved",
    matchScore: 79,
    matchFactors: [
      { factor: "Semantic Similarity", score: 30, maxScore: 40, explanation: "Good match on health analytics domain" },
      { factor: "Domain Compatibility", score: 25, maxScore: 30, explanation: "Health Tech and AI/ML capabilities align" },
      { factor: "Readiness Level", score: 24, maxScore: 30, explanation: "TRL 5, early-stage but promising approach" },
    ],
    submittedAt: "2024-03-10T09:00:00Z",
    updatedAt: "2024-03-25T16:00:00Z",
  },
];

// â”€â”€ Seed Evaluations â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedEvaluations: Evaluation[] = [
  {
    id: "ev_001",
    proposalId: "pr_002",
    evaluatorId: "eval_001",
    challengeId: "ch_002",
    technicalFeasibility: 36,
    cybersecurityDataIsolation: 27,
    costRealism: 25,
    totalScore: 88,
    comments:
      "Exceptionally strong proposal with proven multilingual NLP capabilities. DISHA compliance well-documented. Cost estimates are realistic given the scope. Minor concern: response time SLA needs more rigorous benchmarking on CPGRAMS production load.",
    status: "completed",
    qualifiedForSandbox: true,
    evaluatedAt: "2024-07-10T09:00:00Z",
    createdAt: "2024-07-08T14:00:00Z",
  },
  {
    id: "ev_002",
    proposalId: "pr_003",
    evaluatorId: "eval_002",
    challengeId: "ch_003",
    technicalFeasibility: 34,
    cybersecurityDataIsolation: 26,
    costRealism: 24,
    totalScore: 84,
    comments:
      "Solid blockchain architecture with appropriate use of Hyperledger Fabric. Integration plan with state portals is detailed. Security model for private key management needs strengthening. Recommend sandbox approval with condition on HSM deployment.",
    status: "completed",
    qualifiedForSandbox: true,
    evaluatedAt: "2024-05-20T15:00:00Z",
    createdAt: "2024-05-18T10:00:00Z",
  },
  {
    id: "ev_003",
    proposalId: "pr_004",
    evaluatorId: "eval_001",
    challengeId: "ch_005",
    technicalFeasibility: 30,
    cybersecurityDataIsolation: 24,
    costRealism: 26,
    totalScore: 80,
    comments:
      "Borderline qualified. ML approach is sound but TRL 5 introduces pilot risk. ABDM compliance is a strong positive. Cost is very competitive. Recommend close monitoring during sandbox phase with monthly KPI reviews.",
    status: "completed",
    qualifiedForSandbox: true,
    evaluatedAt: "2024-03-25T16:00:00Z",
    createdAt: "2024-03-22T09:00:00Z",
  },
];

// â”€â”€ Seed Pilots â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedPilots: Pilot[] = [
  {
    id: "pilot_001",
    challengeId: "ch_003",
    proposalId: "pr_003",
    startupId: "st_003",
    startupName: "ChainGuard Systems",
    challengeTitle: "Blockchain-Based Land Records Digitization",
    department: "Ministry of Rural Development",
    startDate: "2024-06-01T00:00:00Z",
    endDate: "2024-11-30T00:00:00Z",
    totalBudget: 2_80_00_000,
    disbursedAmount: 1_10_00_000,
    overallProgress: 48,
    status: "active",
    sandboxEnvironment: "NIC Cloud â€“ Dedicated Blockchain Sandbox VPC",
    createdAt: "2024-05-25T09:00:00Z",
    milestones: [
      {
        id: "ms_001",
        title: "Phase 1: Integration & Setup",
        description: "Hyperledger Fabric network setup, NIC cloud deployment, and integration adapters for Bhu-Naksha and Dharani portals.",
        dueDate: "2024-07-15T00:00:00Z",
        completedDate: "2024-07-12T00:00:00Z",
        trancheAmount: 70_00_000,
        status: "payment_released",
        kpiMetrics: [
          { name: "Portal Integrations Completed", target: 2, achieved: 2, unit: "portals" },
          { name: "Blockchain Nodes Deployed", target: 8, achieved: 8, unit: "nodes" },
          { name: "System Uptime", target: 99.9, achieved: 99.95, unit: "%" },
        ],
      },
      {
        id: "ms_002",
        title: "Phase 2: Pilot District Onboarding",
        description: "Enroll 50,000 land records from 2 pilot districts into the blockchain. Train Tehsildar staff on mutation workflow.",
        dueDate: "2024-09-15T00:00:00Z",
        completedDate: "2024-09-10T00:00:00Z",
        trancheAmount: 40_00_000,
        status: "payment_released",
        kpiMetrics: [
          { name: "Records Enrolled", target: 50000, achieved: 52340, unit: "records" },
          { name: "Staff Trained", target: 120, achieved: 134, unit: "persons" },
          { name: "Avg Mutation Time", target: 7, achieved: 5.2, unit: "days" },
        ],
      },
      {
        id: "ms_003",
        title: "Phase 3: Full District Rollout & Security Audit",
        description: "Complete enrollment of all land records in 4 pilot districts. Independent security audit by CERT-In empanelled agency.",
        dueDate: "2024-10-31T00:00:00Z",
        completedDate: null,
        trancheAmount: 90_00_000,
        status: "in_progress",
        kpiMetrics: [
          { name: "Total Records Enrolled", target: 200000, achieved: 96000, unit: "records" },
          { name: "Fraudulent Mutations Prevented", target: 0, achieved: 0, unit: "cases" },
          { name: "Security Audit Score", target: 90, achieved: null, unit: "points" },
        ],
      },
      {
        id: "ms_004",
        title: "Phase 4: Evaluation & Procurement Report",
        description: "Final KPI evaluation, impact assessment, and procurement recommendation report for national scaling.",
        dueDate: "2024-11-30T00:00:00Z",
        completedDate: null,
        trancheAmount: 80_00_000,
        status: "pending",
        kpiMetrics: [
          { name: "Overall KPI Achievement", target: 90, achieved: null, unit: "%" },
          { name: "States Ready for Scaling", target: 5, achieved: null, unit: "states" },
        ],
      },
    ],
  },
  {
    id: "pilot_002",
    challengeId: "ch_005",
    proposalId: "pr_004",
    startupId: "st_005",
    startupName: "HealthPredict Analytics",
    challengeTitle: "Predictive Health Analytics for District Hospitals",
    department: "Ministry of Health & Family Welfare",
    startDate: "2024-04-15T00:00:00Z",
    endDate: "2024-10-14T00:00:00Z",
    totalBudget: 95_00_000,
    disbursedAmount: 75_00_000,
    overallProgress: 85,
    status: "active",
    sandboxEnvironment: "AWS GovCloud â€“ Health Analytics Sandbox",
    createdAt: "2024-04-10T09:00:00Z",
    milestones: [
      {
        id: "ms_005",
        title: "Phase 1: Data Pipeline & Model Training",
        description: "HMIS data integration, historical data ingestion, and initial model training.",
        dueDate: "2024-05-31T00:00:00Z",
        completedDate: "2024-05-28T00:00:00Z",
        trancheAmount: 25_00_000,
        status: "payment_released",
        kpiMetrics: [
          { name: "Hospitals Integrated", target: 10, achieved: 10, unit: "hospitals" },
          { name: "Historical Records Processed", target: 500000, achieved: 620000, unit: "records" },
          { name: "Initial Model Accuracy", target: 80, achieved: 83.5, unit: "%" },
        ],
      },
      {
        id: "ms_006",
        title: "Phase 2: Deployment & Staff Training",
        description: "Dashboard deployment, CMO onboarding, and automated procurement trigger setup.",
        dueDate: "2024-07-31T00:00:00Z",
        completedDate: "2024-07-25T00:00:00Z",
        trancheAmount: 30_00_000,
        status: "payment_released",
        kpiMetrics: [
          { name: "CMOs Trained", target: 10, achieved: 10, unit: "persons" },
          { name: "Automated Reorder Triggers Configured", target: 50, achieved: 48, unit: "medicines" },
          { name: "Dashboard Uptime", target: 99.5, achieved: 99.8, unit: "%" },
        ],
      },
      {
        id: "ms_007",
        title: "Phase 3: Validation & Impact Assessment",
        description: "3-month live validation of predictions against actuals, medicine stockout reduction measurement.",
        dueDate: "2024-09-30T00:00:00Z",
        completedDate: "2024-09-28T00:00:00Z",
        trancheAmount: 20_00_000,
        status: "payment_released",
        kpiMetrics: [
          { name: "Prediction Accuracy (Weekly Load)", target: 85, achieved: 87.2, unit: "%" },
          { name: "Stockout Reduction", target: 70, achieved: 74, unit: "%" },
          { name: "Bed Optimization Improvement", target: 20, achieved: 23, unit: "%" },
        ],
      },
      {
        id: "ms_008",
        title: "Phase 4: Final Report & Scaling Plan",
        description: "Comprehensive impact report and detailed scaling plan for 200 district hospitals.",
        dueDate: "2024-10-14T00:00:00Z",
        completedDate: null,
        trancheAmount: 20_00_000,
        status: "in_progress",
        kpiMetrics: [
          { name: "Pilot Success Score", target: 80, achieved: null, unit: "points" },
          { name: "Scaling Plan Districts", target: 200, achieved: null, unit: "districts" },
        ],
      },
    ],
  },
];

// â”€â”€ Seed Procurement Items â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedProcurements: ProcurementItem[] = [
  {
    id: "proc_001",
    pilotId: "pilot_002",
    challengeId: "ch_005",
    startupId: "st_005",
    startupName: "HealthPredict Analytics",
    solutionTitle: "HP-Analytics: Predictive District Health Resource Optimizer",
    department: "Ministry of Health & Family Welfare",
    domains: ["Health Tech", "AI/ML", "Data Analytics"],
    pilotSuccessScore: 87,
    kpiAchievement: 94,
    procurementValue: 8_50_00_000,
    replicableFor: [
      "Ministry of Tribal Affairs",
      "State Health Departments",
      "Ayushman Bharat â€“ PMJAY",
      "NHM District Health Societies",
    ],
    description:
      "AI-powered predictive analytics platform for district hospital resource planning. Successfully reduced medicine stockouts by 74%, improved bed optimization by 23%, and achieved 87.2% prediction accuracy across 10 pilot hospitals in Madhya Pradesh.",
    certifiedAt: "2024-10-01T09:00:00Z",
    tags: ["Health Analytics", "Predictive AI", "ABDM Compliant", "NHM Ready", "Proven Pilot"],
  },
];

// â”€â”€ Seed Changelog â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const seedChangelog: ChangelogEntry[] = [
  {
    id: "log_001",
    timestamp: "2024-01-15T09:00:00Z",
    actor: "System",
    role: "admin",
    action: "PLATFORM_INITIALIZED",
    entityType: "system",
    entityId: "govsetu_v1",
    details: "GovSetu Platform v1.0.0 initialized. Design system tokens configured: Navy #1E3A8A, Royal Blue #2563EB, Emerald #10B981, Amber #F59E0B.",
  },
  {
    id: "log_002",
    timestamp: "2024-01-05T09:30:00Z",
    actor: "Gov. Officer Ramesh Iyer",
    role: "government",
    action: "CHALLENGE_PUBLISHED",
    entityType: "challenge",
    entityId: "ch_005",
    details: "Challenge 'Predictive Health Analytics for District Hospital Resource Planning' published by Ministry of Health & Family Welfare. Budget: â‚¹4 Cr. Deadline: 31 March 2024.",
  },
  {
    id: "log_003",
    timestamp: "2024-03-10T09:00:00Z",
    actor: "HealthPredict Analytics",
    role: "startup",
    action: "PROPOSAL_SUBMITTED",
    entityType: "proposal",
    entityId: "pr_004",
    details: "Proposal submitted by HealthPredict Analytics (DPIIT245678) for Challenge ch_005. TRL Level: 5. Estimated Cost: â‚¹95L. Match Score: 79%.",
  },
  {
    id: "log_004",
    timestamp: "2024-03-25T16:00:00Z",
    actor: "Evaluator Dr. Priya Nair",
    role: "evaluator",
    action: "EVALUATION_COMPLETED",
    entityType: "evaluation",
    entityId: "ev_003",
    details: "Blind evaluation completed for Proposal pr_004. Score: 80/100 (Technical: 30, Cybersecurity: 24, Cost: 26). Qualified for Sandbox: YES.",
  },
  {
    id: "log_005",
    timestamp: "2024-04-10T09:00:00Z",
    actor: "Gov. Officer Ramesh Iyer",
    role: "government",
    action: "PILOT_INITIATED",
    entityType: "pilot",
    entityId: "pilot_002",
    details: "Sandbox Pilot initiated for HealthPredict Analytics. Total Budget: â‚¹95L. Duration: 6 months (Aprilâ€“October 2024). Environment: AWS GovCloud.",
  },
  {
    id: "log_006",
    timestamp: "2024-05-28T14:30:00Z",
    actor: "Gov. Officer Ramesh Iyer",
    role: "government",
    action: "MILESTONE_PAYMENT_RELEASED",
    entityType: "pilot",
    entityId: "pilot_002",
    details: "Tranche 1 payment of â‚¹25L released for Milestone 'Phase 1: Data Pipeline & Model Training'. All KPIs achieved: 10/10 hospitals integrated, 83.5% model accuracy.",
  },
  {
    id: "log_007",
    timestamp: "2024-06-01T09:00:00Z",
    actor: "System",
    role: "admin",
    action: "PILOT_INITIATED",
    entityType: "pilot",
    entityId: "pilot_001",
    details: "Sandbox Pilot initiated for ChainGuard Systems (Blockchain Land Records). Budget: â‚¹2.8 Cr. Duration: 6 months.",
  },
  {
    id: "log_008",
    timestamp: "2024-07-12T16:00:00Z",
    actor: "Gov. Officer Sunita Sharma",
    role: "government",
    action: "MILESTONE_PAYMENT_RELEASED",
    entityType: "pilot",
    entityId: "pilot_001",
    details: "Tranche 1 payment of â‚¹70L released for ChainGuard Systems. Phase 1 (Integration & Setup) completed ahead of schedule. All 8 blockchain nodes operational.",
  },
  {
    id: "log_009",
    timestamp: "2024-10-01T09:00:00Z",
    actor: "System â€“ Procurement Engine",
    role: "admin",
    action: "SOLUTION_CERTIFIED_FOR_PROCUREMENT",
    entityType: "procurement",
    entityId: "proc_001",
    details: "HealthPredict Analytics solution certified for cross-departmental procurement. Pilot Success Score: 87/100. KPI Achievement: 94%. Procurement Value: â‚¹8.5 Cr.",
  },
];
